### PR TITLE
Update hn_check.py. AttributeError fix.

### PR DESCRIPTION
**Pull request by HeavensGold**
Following 'psutil' Error fixed:
AttributeError: 'Process' object has no attribute 'rlimit'

### CODE REVIEW

**Comment by EggPool** [comment]
Hi,

Thanks for the feedback.

What os / psutil version are you on?
process.rlimit() does exists:
https://psutil.readthedocs.io/en/latest/#psutil.Process.rlimit

Works for all regular installs I saw until now.
Can use resource module instead for this specific use, but since psutil is used for other things, better avoid one more import.

**Comment by HeavensGold** [comment]
Ubuntu 16.04 64bit.
Python 3.6.5 Anaconda.
psutil 5.4.5
There is no rlimit method in this environment. At least, two my PCs with the same environment failed to find rlimit. 

Well, I found that <Ubuntu 18.04, regular python 3.6.5, psutil 5.4.7>  has rlimit method.
Probably psutil version 5.4.5 has the problem. However, 5.4.5 is currently the latest version in Anaconda package(or ubuntu 16.04).

Thank you for the comment.

**Comment by EggPool** [comment]
Ok, I'll move to resource.
Tested and it's ok with regular Python too.
I did not test with Anaconda. rlimit seems to be in the 5.4.5 psutil code, but may depend on compilation defines.
Merging, then adjusting hn_client too and cleaning up.

Thanks a lot!

**Comment by EggPool** [comment]
@HeavensGold Unrelated: are you familiar with electrum forks? If yes, can you contact me via the discord or twitter?

**Pull request merged**
